# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.validators import RegexValidator
from django.contrib.postgres.fields import ArrayField


# Create your models here.
class Member(models.Model):
    firstname = models.CharField(max_length=40, blank=False)
    lastname = models.CharField(max_length=40, blank=False)
    mobile_number = models.CharField(max_length=10, blank=True)
    description = models.TextField(max_length=255, blank=False)
    location = models.TextField(max_length=255, blank=False)
    date = models.DateField('%m/%d/%Y')
    created_at = models.DateTimeField('%m/%d/%Y %H:%M:%S')
    updated_at = models.DateTimeField('%m/%d/%Y %H:%M:%S')

    def __str__(self):
        return self.firstname

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.CharField(max_length=255, )
    uploaded_at = models.DateTimeField(auto_now_add=True)

class Ajax(models.Model):
    text = models.CharField(max_length=255, blank=True)
    search = models.CharField(max_length=255)
    email = models.EmailField(max_length=254)
    telephone = models.CharField(max_length=10, blank=True)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

class CsvUpload(models.Model):
    name = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    end_date = models.DateTimeField()
    notes = models.CharField(max_length=255, blank=True)


class PatientOverallMedicalDetails(models.Model):
    fullname = models.CharField(max_length=255, blank=False)
    organization = models.CharField(max_length=255, blank=False)
    address = models.CharField(max_length=255, blank=True)
    department = models.TextField(max_length=255, blank=False)
    id_mark = models.TextField(max_length=255, blank=False)
    date = models.DateField('%m/%d/%Y')
    gender = models.CharField(max_length=255, blank=True)
    married_stat = models.CharField(max_length=255, blank=True)
    desig = models.CharField(max_length=255, blank=True)
    age = models.CharField(max_length=255, blank=True)
    dob = models.DateField('%m/%d/%Y')
    present_complains = models.TextField(max_length=255, blank=False)

    # short_breath    = models.BooleanField(null=True,default=False)
    # weight_loss = models.BooleanField(null=True,default=False)
    # fainting_spells = models.BooleanField(null=True,default=False)
    # freq_headache = models.BooleanField(null=True,default=False)
    # chest_pain = models.BooleanField(null=True,default=False)
    # hearing_disturb = models.BooleanField(null=True,default=False)
    # freq_cold = models.BooleanField(null=True,default=False)
    # urinary_disturb = models.BooleanField(null=True,default=False)
    # visual_disturb = models.BooleanField(null=True,default=False)
    # swelling_ankle = models.BooleanField(null=True,default=False)
    # vertigo = models.BooleanField(null=True,default=False)
    # joint_pains = models.BooleanField(null=True,default=False)

    self_hypertension =     models.BooleanField(null=True,default=False)
    self_diabetes =         models.BooleanField(null=True,default=False)
    self_heartdisease =     models.BooleanField(null=True,default=False)
    self_tuberculosis =     models.BooleanField(null=True,default=False)
    self_cancer =           models.BooleanField(null=True,default=False)
    self_asthama =          models.BooleanField(null=True,default=False)
    self_stroke =           models.BooleanField(null=True,default=False)
    self_epilepsy =         models.BooleanField(null=True,default=False)
    father_hypertension =   models.BooleanField(null=True,default=False)
    father_diabetes =       models.BooleanField(null=True,default=False)
    father_heartdisease =   models.BooleanField(null=True,default=False)
    father_tuberculosis =   models.BooleanField(null=True,default=False)
    father_cancer =         models.BooleanField(null=True,default=False)
    father_asthama =        models.BooleanField(null=True,default=False)
    father_stroke =         models.BooleanField(null=True,default=False)
    father_epilepsy =       models.BooleanField(null=True,default=False)
    mother_hypertension =   models.BooleanField(null=True,default=False)
    mother_diabetes =       models.BooleanField(null=True,default=False)
    mother_heartdisease =   models.BooleanField(null=True,default=False)
    mother_tuberculosis =   models.BooleanField(null=True,default=False)
    mother_cancer =         models.BooleanField(null=True,default=False)
    mother_asthama =        models.BooleanField(null=True,default=False)
    mother_stroke =         models.BooleanField(null=True,default=False)
    mother_epilepsy =       models.BooleanField(null=True,default=False)

    prev_surgiory   = models.CharField(max_length=255,blank=True)
    nos_of_child   = models.CharField(max_length=255,blank=True)
    diet   = models.CharField(max_length=255,blank=True)
    addictions   = ArrayField(models.CharField(max_length=255), null=True, blank=True)
    bowel_habits   = models.CharField(max_length=255,blank=True)
    exercise   = models.CharField(max_length=255,blank=True)
    present_comp_name   = models.CharField(max_length=255,blank=True)
    present_years_worked   = models.CharField(max_length=255,blank=True)
    present_job_nature   = models.CharField(max_length=255,blank=True)
    previous_comp_name   = models.CharField(max_length=255,blank=True)
    previous_years_worked   = models.CharField(max_length=255,blank=True)
    previous_job_nature   = models.CharField(max_length=255,blank=True)
    exposed_to_occupational_hazards   = ArrayField(models.CharField(max_length=255), null=True, blank=True)
    height   = models.CharField(max_length=255,blank=True)
    chest_inspiration   = models.CharField(max_length=255,blank=True)
    abdominal_girth   = models.CharField(max_length=255,blank=True)
    weight   = models.CharField(max_length=255,blank=True)
    expiration   = models.CharField(max_length=255,blank=True)
    bmi   = models.CharField(max_length=255,blank=True)
    external_exam   = models.CharField(max_length=255,blank=True)
    squint_nystagmus   = models.CharField(max_length=255,blank=True)
    colour_vision   = models.CharField(max_length=255,blank=True)
    without_glasses_re   = models.CharField(max_length=255,blank=True)
    with_glasses_re   = models.CharField(max_length=255,blank=True)
    without_glasses_le   = models.CharField(max_length=255,blank=True)
    with_glasses_le   = models.CharField(max_length=255,blank=True)
    without_glasses_re_near   = models.CharField(max_length=255,blank=True)
    with_glasses_re_near   = models.CharField(max_length=255,blank=True)
    without_glasses_le_near   = models.CharField(max_length=255,blank=True)
    with_glasses_le_near   = models.CharField(max_length=255,blank=True)
    built   = models.CharField(max_length=255,blank=True)
    teeth   = models.CharField(max_length=255,blank=True)
    throat   = models.CharField(max_length=255,blank=True)
    tongue   = models.CharField(max_length=255,blank=True)
    lymph_nodes   = models.CharField(max_length=255,blank=True)
    pallor   = models.CharField(max_length=255,blank=True)
    edema   = models.CharField(max_length=255,blank=True)
    thyroid   = models.CharField(max_length=255,blank=True)
    tonsils   = models.CharField(max_length=255,blank=True)
    gums   = models.CharField(max_length=255,blank=True)
    nails   = models.CharField(max_length=255,blank=True)
    icterus   = models.CharField(max_length=255,blank=True)
    clubbing   = models.CharField(max_length=255,blank=True)
    ecg   = models.CharField(max_length=255,blank=True)
    pulse   = models.CharField(max_length=255,blank=True)
    pulse_stat   = models.CharField(max_length=255,blank=True)
    blood_pressure   = models.CharField(max_length=255,blank=True)
    heart_sounds   = models.CharField(max_length=255,blank=True)
    peripheral_pulsations   = models.CharField(max_length=255,blank=True)
    murmur   = models.CharField(max_length=255,blank=True)
    # respiratory_system   = models.CharField(max_length=255,blank=True)
    chest_shape  = models.CharField(max_length=255,blank=True)
    trachea  = models.CharField(max_length=255,blank=True)
    chest_movements  = models.CharField(max_length=255,blank=True)
    breath_sounds  = models.CharField(max_length=255,blank=True)
    adventious_sounds  = models.CharField(max_length=255,blank=True)
    liver   = models.CharField(max_length=255,blank=True)
    abdominal_lumps   = models.CharField(max_length=255,blank=True)
    spleen   = models.CharField(max_length=255,blank=True)
    external_examination = models.CharField(max_length=255,blank=True)
    conversational_hearing = models.CharField(max_length=255,blank=True)
    # examination_ear_nose_throat   = models.CharField(max_length=255,blank=True)
    # central_nervous_system   = models.CharField(max_length=255,blank=True)
    skin   = models.CharField(max_length=255,blank=True)
    remarks   = models.CharField(max_length=255,blank=True)
    advice   = models.CharField(max_length=255,blank=True)
    higher_function = models.CharField(max_length=100,blank=True)
    sensory_system = models.CharField(max_length=100,blank=True)
    tendon_reflexes = models.CharField(max_length=100,blank=True)
    poisture = models.CharField(max_length=100,blank=True)
    pshyco_makeup = models.CharField(max_length=100,blank=True)
    cranial_nerves = models.CharField(max_length=100,blank=True)
    motor_function = models.CharField(max_length=100,blank=True)
    spine = models.CharField(max_length=100,blank=True)
    gait = models.CharField(max_length=100,blank=True)
    waist = models.CharField(max_length=100,blank=True)
    hip = models.CharField(max_length=100,blank=True)
    # waist_hip_ratio = models.CharField(max_length=100,blank=True)
    

    def __str__(self):
        return self.fullname


class Form7Details(models.Model):
    dept_name = models.CharField(max_length=100, blank=True)
    date = models.DateField('%m/%d/%Y')
    hazard = models.CharField(max_length=100, blank=True)
    danger = models.CharField(max_length=100, blank=True)
    job = models.CharField(max_length=100, blank=True)
    raw = models.CharField(max_length=100, blank=True)
    posting_date = models.DateField('%m/%d/%Y')
    leaving_date = models.DateField('%m/%d/%Y')
    discharge_reason = models.CharField(max_length=100, blank=True)
    discahrge_date = models.DateField('%m/%d/%Y')
    symptons = models.CharField(max_length=100, blank=True)
    test_nature = models.CharField(max_length=100, blank=True)
    results = models.CharField(max_length=100, blank=True)
    temp_withdraw = models.CharField(max_length=100, blank=True)
    reason_withdraw = models.CharField(max_length=100, blank=True)
    unfit_date = models.DateField('%m/%d/%Y')
    fitness_date = models.DateField('%m/%d/%Y')
    patient_id = models.ForeignKey(PatientOverallMedicalDetails,models.CASCADE)
    patient_name = models.CharField(max_length=100,blank=True)


class BloodUrineXRay(models.Model):
    patient_id = models.ForeignKey(PatientOverallMedicalDetails,models.CASCADE)
    patient_name = models.CharField(max_length=100,blank=True)
    date = models.DateField('%m/%d/%Y')
    # age = models.CharField(max_length=100, blank=True)
    # gender = models.CharField(max_length=100, blank=True)

    hb = models.CharField(max_length=100, blank=True)
    wbc = models.CharField(max_length=100, blank=True)
    diff_wb = models.CharField(max_length=100, blank=True)
    neutrophils = models.CharField(max_length=100, blank=True)
    lymphocytes = models.CharField(max_length=100, blank=True)
    eosinophils = models.CharField(max_length=100, blank=True)
    monocytes = models.CharField(max_length=100, blank=True)
    basophil = models.CharField(max_length=100, blank=True)
    total_rbc = models.CharField(max_length=100, blank=True)
    platelet_count = models.CharField(max_length=100, blank=True)
    esr = models.CharField(max_length=100, blank=True)
    rbsl = models.CharField(max_length=100, blank=True)
    blood_group = models.CharField(max_length=100, blank=True)
       ##urine exam
    urine_colour      = models.CharField(max_length=100, blank=True)
    urine_appearance = models.CharField(max_length=100, blank=True)
    urine_odour = models.CharField(max_length=100, blank=True)
    urine_ph = models.CharField(max_length=100, blank=True)
    urine_gravity = models.CharField(max_length=100, blank=True)
    urine_deposits = models.CharField(max_length=100, blank=True)
    urine_protein = models.CharField(max_length=100, blank=True)
    urine_sugar = models.CharField(max_length=100, blank=True)

    ##Microscop
    microscopic_pus_cell         = models.CharField(max_length=100, blank=True)
    microscopic_epithelial_cell = models.CharField(max_length=100, blank=True)
    microscopic_rbc_cells = models.CharField(max_length=100, blank=True)
    microscopic_crystals = models.CharField(max_length=100, blank=True)
    microscopic_cast = models.CharField(max_length=100, blank=True)
    microscopic_other_findings = models.CharField(max_length=100, blank=True)

    xray_view = models.TextField(blank=True)

    opinion = models.CharField(max_length=100, blank=True)

    total_cholesterol      = models.CharField(max_length=100, blank=True)
    triglycerides = models.CharField(max_length=100, blank=True)
    hdl = models.CharField(max_length=100, blank=True)
    ldl = models.CharField(max_length=100, blank=True)
    vldl = models.CharField(max_length=100, blank=True)
    sgot = models.CharField(max_length=100, blank=True)
    sgpt = models.CharField(max_length=100, blank=True)
    blood_urea = models.CharField(max_length=100, blank=True)
    se_creatinin = models.CharField(max_length=100, blank=True)
    bilirubin_total = models.CharField(max_length=100, blank=True)
    bilirubin_dierct = models.CharField(max_length=100, blank=True)
    alkaline_phosphatase = models.CharField(max_length=100, blank=True)

    uric_acid            = models.CharField(max_length=100, blank=True)
    fbsl = models.CharField(max_length=100, blank=True)
    ppbsl = models.CharField(max_length=100, blank=True)
    ldl_hdl_ratio = models.CharField(max_length=100, blank=True)
    chol_hdl_ratio = models.CharField(max_length=100, blank=True)
    total_protein = models.CharField(max_length=100, blank=True)
    albumin = models.CharField(max_length=100, blank=True)
    globumin = models.CharField(max_length=100, blank=True)
    bilirubin_indierct = models.CharField(max_length=100, blank=True)




class StoolReport(models.Model):
    patient_id = models.ForeignKey(PatientOverallMedicalDetails,models.CASCADE, related_name='patient_id')
    patient_name = models.CharField(max_length=100,blank=True)
    date = models.DateField('%m/%d/%Y')
    # age = models.CharField(max_length=100, blank=True)
    # gender = models.CharField(max_length=100, blank=True)

    
    ##General exam
    colour                = models.CharField(max_length=100, blank=True)
    consistency    = models.CharField(max_length=100, blank=True)
    mucus         = models.CharField(max_length=100, blank=True)
    parasites            = models.CharField(max_length=100, blank=True)
    frank_blood       = models.CharField(max_length=100, blank=True)
    occult_blood      = models.CharField(max_length=100, blank=True)
    # stercobilinogen       = models.CharField(max_length=100, blank=True)
    reaction_pH         = models.CharField(max_length=100, blank=True)

    ##Microscope
    microscope_epithelial_cells         = models.CharField(max_length=100, blank=True)    
    microscope_pus_cells  = models.CharField(max_length=100, blank=True)
    microscope_rbs_cells        = models.CharField(max_length=100, blank=True)
    microscope_protozoa         = models.CharField(max_length=100, blank=True)
    microscope_ova             = models.CharField(max_length=100, blank=True)
    microscope_other_findings   = models.CharField(max_length=100, blank=True)

    ###Widal report

    widal_salmonella_O  = models.CharField(max_length=100, blank=True)
    widal_salmonella_H  = models.CharField(max_length=100, blank=True)
    widal_salmonella_AH  = models.CharField(max_length=100, blank=True)
    widal_salmonella_BH  = models.CharField(max_length=100, blank=True)

    hep_A               = models.CharField(max_length=100, blank=True)
    hep_B               = models.CharField(max_length=100, blank=True)
    hep_C               = models.CharField(max_length=100, blank=True)
    vdrl                = models.CharField(max_length=100, blank=True)
    hiv1                = models.CharField(max_length=100, blank=True)
    hiv2                = models.CharField(max_length=100, blank=True)
    sputum                = models.CharField(max_length=100, blank=True)




class Audiometry(models.Model):

    patient_name = models.ForeignKey(PatientOverallMedicalDetails,models.CASCADE)
    date         = models.DateField('%m/%d/%Y')
    le_ear_125   = models.IntegerField()
    le_ear_250      = models.IntegerField()
    le_ear_500   = models.IntegerField()
    le_ear_1K   = models.IntegerField()
    le_ear_2K   = models.IntegerField()
    le_ear_4K   = models.IntegerField()
    le_ear_6K   = models.IntegerField()
    le_ear_8K   = models.IntegerField()
    re_ear_125  = models.IntegerField()
    re_ear_250  = models.IntegerField()
    re_ear_500  = models.IntegerField()
    re_ear_1K   = models.IntegerField()
    re_ear_2K   = models.IntegerField()
    re_ear_4K   = models.IntegerField()
    re_ear_6K   = models.IntegerField()
    re_ear_8K   = models.IntegerField()


    bone_le_ear_250 = models.IntegerField()
    bone_le_ear_500 = models.IntegerField()
    bone_le_ear_1K = models.IntegerField()
    bone_le_ear_2K = models.IntegerField()
    bone_le_ear_4K = models.IntegerField()
    bone_re_ear_250 = models.IntegerField()
    bone_re_ear_500 = models.IntegerField()
    bone_re_ear_1K = models.IntegerField()
    bone_re_ear_2K = models.IntegerField()
    bone_re_ear_4K = models.IntegerField()