# Generated by Django 3.1.3 on 2020-11-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_patientoverallmedicaldetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
