# Generated by Django 3.1.3 on 2020-11-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20201128_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form7Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, max_length=100)),
                ('hazard', models.CharField(blank=True, max_length=100)),
                ('danger', models.CharField(blank=True, max_length=100)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('raw', models.CharField(blank=True, max_length=100)),
                ('posting_date', models.DateField(verbose_name='%m/%d/%Y')),
                ('leaving_date', models.DateField(verbose_name='%m/%d/%Y')),
                ('discharge_reason', models.CharField(blank=True, max_length=100)),
                ('discahrge_date', models.DateField(verbose_name='%m/%d/%Y')),
                ('symptons', models.CharField(blank=True, max_length=100)),
                ('test_nature', models.CharField(blank=True, max_length=100)),
                ('results', models.CharField(blank=True, max_length=100)),
                ('temp_withdraw', models.CharField(blank=True, max_length=100)),
                ('reason_withdraw', models.CharField(blank=True, max_length=100)),
                ('unfit_date', models.DateField(verbose_name='%m/%d/%Y')),
                ('fitness_date', models.DateField(verbose_name='%m/%d/%Y')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.patientoverallmedicaldetails')),
            ],
        ),
    ]
