# Generated by Django 3.1.3 on 2020-12-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_form7details'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoolReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='%m/%d/%Y')),
                ('age', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('consistency', models.CharField(blank=True, max_length=100)),
                ('mucus', models.CharField(blank=True, max_length=100)),
                ('parasites', models.CharField(blank=True, max_length=100)),
                ('frank_blood', models.CharField(blank=True, max_length=100)),
                ('occult_blood', models.CharField(blank=True, max_length=100)),
                ('stercobilinogen', models.CharField(blank=True, max_length=100)),
                ('reaction_pH', models.CharField(blank=True, max_length=100)),
                ('microscope_epithelial_cells', models.CharField(blank=True, max_length=100)),
                ('microscope_pus_cells', models.CharField(blank=True, max_length=100)),
                ('microscope_rbs_cells', models.CharField(blank=True, max_length=100)),
                ('microscope_protozoa', models.CharField(blank=True, max_length=100)),
                ('microscope_ova', models.CharField(blank=True, max_length=100)),
                ('microscope_other_findings', models.CharField(blank=True, max_length=100)),
                ('widal_salmonella_O', models.CharField(blank=True, max_length=100)),
                ('widal_salmonella_H', models.CharField(blank=True, max_length=100)),
                ('widal_salmonella_AH', models.CharField(blank=True, max_length=100)),
                ('widal_salmonella_BH', models.CharField(blank=True, max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.patientoverallmedicaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='BloodUrineXRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='%m/%d/%Y')),
                ('age', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('hb', models.CharField(blank=True, max_length=100)),
                ('wbc', models.CharField(blank=True, max_length=100)),
                ('diff_wb', models.CharField(blank=True, max_length=100)),
                ('neutrophils', models.CharField(blank=True, max_length=100)),
                ('lymphocytes', models.CharField(blank=True, max_length=100)),
                ('eosinophils', models.CharField(blank=True, max_length=100)),
                ('monocytes', models.CharField(blank=True, max_length=100)),
                ('basophil', models.CharField(blank=True, max_length=100)),
                ('total_rbc', models.CharField(blank=True, max_length=100)),
                ('platelet_count', models.CharField(blank=True, max_length=100)),
                ('esr', models.CharField(blank=True, max_length=100)),
                ('rbsl', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=100)),
                ('urine_colour', models.CharField(blank=True, max_length=100)),
                ('urine_appearance', models.CharField(blank=True, max_length=100)),
                ('urine_odour', models.CharField(blank=True, max_length=100)),
                ('urine_ph', models.CharField(blank=True, max_length=100)),
                ('urine_gravity', models.CharField(blank=True, max_length=100)),
                ('urine_deposits', models.CharField(blank=True, max_length=100)),
                ('urine_protein', models.CharField(blank=True, max_length=100)),
                ('urine_sugar', models.CharField(blank=True, max_length=100)),
                ('microscopic_pus_cell', models.CharField(blank=True, max_length=100)),
                ('microscopic_epithelial_cell', models.CharField(blank=True, max_length=100)),
                ('microscopic_rbc_cells', models.CharField(blank=True, max_length=100)),
                ('microscopic_crystals', models.CharField(blank=True, max_length=100)),
                ('microscopic_cast', models.CharField(blank=True, max_length=100)),
                ('microscopic_other_findings', models.CharField(blank=True, max_length=100)),
                ('xray_view', models.CharField(blank=True, max_length=100)),
                ('opinion', models.CharField(blank=True, max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.patientoverallmedicaldetails')),
            ],
        ),
    ]
