# Generated by Django 3.1.3 on 2020-12-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_bloodurinexray_stoolreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='father_asthama',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='father_cancer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='father_diabetes',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='father_heartdisease',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='father_hypertension',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='father_stroke',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='father_tuberculosis',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='mother_asthama',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='mother_cancer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='mother_diabetes',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='mother_heartdisease',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='mother_hypertension',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='mother_stroke',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='mother_tuberculosis',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='self_asthama',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='self_cancer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='self_diabetes',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='self_heartdisease',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='self_hypertension',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='self_stroke',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='self_tuberculosis',
            field=models.BooleanField(null=True),
        ),
    ]
