# Generated by Django 3.1.3 on 2020-12-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_auto_20201206_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='abdominal_girth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='abdominal_lumps',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='addictions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='advice',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='bmi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='bowel_habits',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='built',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='central_nervous_system',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='chest_inspiration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='colour_vision',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='diet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='edema',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='examination_ear_nose_throat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='exercise',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='expiration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='exposed_to_occupational_hazards',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='external_exam',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='gums',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='heart_sounds',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='height',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='icterus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='liver',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='lymph_nodes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='murmur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='nails',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='nos_of_child',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='pallor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='peripheral_pulsations',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='present_comp_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='present_job_nature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='present_years_worked',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='prev_surgiory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='previous_comp_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='previous_job_nature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='previous_years_worked',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='pulse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='respiratory_system',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='skin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='spleen',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='squint_nystagmus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='teeth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='throat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='thyroid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='tongue',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='tonsils',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='weight',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='with_glasses_le',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='with_glasses_le_near',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='with_glasses_re',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='with_glasses_re_near',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='without_glasses_le',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='without_glasses_le_near',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='without_glasses_re',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='without_glasses_re_near',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
