# Generated by Django 3.1.3 on 2020-12-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_auto_20201209_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodurinexray',
            name='age',
        ),
        migrations.RemoveField(
            model_name='bloodurinexray',
            name='gender',
        ),
    ]
