# Generated by Django 3.1.3 on 2020-12-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_auto_20201213_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodurinexray',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
