# Generated by Django 3.1.3 on 2020-12-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_auto_20201213_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodurinexray',
            name='age',
        ),
        migrations.RemoveField(
            model_name='bloodurinexray',
            name='gender',
        ),
    ]
