# Generated by Django 3.1.3 on 2020-12-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_auto_20201213_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoolreport',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to='crud.patientoverallmedicaldetails'),
        ),
    ]
