# Generated by Django 3.1.3 on 2020-12-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_auto_20201213_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='%m/%d/%Y')),
                ('le_ear_125', models.IntegerField()),
                ('le_ear_250', models.IntegerField()),
                ('le_ear_500', models.IntegerField()),
                ('le_ear_1K', models.IntegerField()),
                ('le_ear_2K', models.IntegerField()),
                ('le_ear_4K', models.IntegerField()),
                ('le_ear_6K', models.IntegerField()),
                ('le_ear_8K', models.IntegerField()),
                ('re_ear_125', models.IntegerField()),
                ('re_ear_250', models.IntegerField()),
                ('re_ear_500', models.IntegerField()),
                ('re_ear_1K', models.IntegerField()),
                ('re_ear_2K', models.IntegerField()),
                ('re_ear_4K', models.IntegerField()),
                ('re_ear_6K', models.IntegerField()),
                ('re_ear_8K', models.IntegerField()),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.patientoverallmedicaldetails')),
            ],
        ),
    ]
