# Generated by Django 3.1.3 on 2020-12-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_audiometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiometry',
            name='bone_le_ear_1K',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiometry',
            name='bone_le_ear_250',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiometry',
            name='bone_le_ear_2K',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiometry',
            name='bone_le_ear_4K',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiometry',
            name='bone_le_ear_500',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiometry',
            name='bone_re_ear_1K',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiometry',
            name='bone_re_ear_250',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiometry',
            name='bone_re_ear_2K',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiometry',
            name='bone_re_ear_4K',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiometry',
            name='bone_re_ear_500',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
