# Generated by Django 3.1.3 on 2020-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_auto_20201215_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodurinexray',
            name='alkaline_phosphatase',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='bilirubin_dierct',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='bilirubin_total',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='blood_urea',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='hdl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='ldl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='se_creatinin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='sgot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='sgpt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='total_cholesterol',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='triglycerides',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodurinexray',
            name='vldl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
