# Generated by Django 3.1.3 on 2021-01-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_auto_20210110_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='addictions',
        ),
    ]
