# Generated by Django 3.1.3 on 2021-01-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0024_auto_20210110_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='clubbing',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
