# Generated by Django 3.1.3 on 2021-01-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0025_patientoverallmedicaldetails_clubbing'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='ecg',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
