# Generated by Django 3.1.3 on 2021-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0026_patientoverallmedicaldetails_ecg'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='pulse_stat',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
