# Generated by Django 3.1.3 on 2021-01-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0027_patientoverallmedicaldetails_pulse_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='central_nervous_system',
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='cranial_nerves',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='gait',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='higher_function',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='motor_function',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='poisture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='pshyco_makeup',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='sensory_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='spine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='tendon_reflexes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
