# Generated by Django 3.1.3 on 2021-01-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0028_auto_20210110_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientoverallmedicaldetails',
            old_name='examination_ear_nose_throat',
            new_name='conversational_hearing',
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='external_examination',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
