# Generated by Django 3.1.3 on 2021-01-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0029_auto_20210110_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientoverallmedicaldetails',
            old_name='respiratory_system',
            new_name='adventious_sounds',
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='breath_sounds',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='chest_movements',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='chest_shape',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='trachea',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
