# Generated by Django 3.1.3 on 2021-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0030_auto_20210110_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='hip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='waist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientoverallmedicaldetails',
            name='waist_hip_ratio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
