# Generated by Django 3.1.3 on 2021-01-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0032_auto_20210110_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoolreport',
            name='stercobilinogen',
        ),
    ]
