# Generated by Django 3.1.3 on 2021-01-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0033_remove_stoolreport_stercobilinogen'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoolreport',
            name='conf',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stoolreport',
            name='hep_A',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stoolreport',
            name='hep_B',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stoolreport',
            name='hep_C',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stoolreport',
            name='hiv1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stoolreport',
            name='hiv2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stoolreport',
            name='vdrl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
