# Generated by Django 3.1.3 on 2021-01-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0035_auto_20210117_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stoolreport',
            old_name='conf',
            new_name='sputum',
        ),
    ]
