# Generated by Django 3.1.3 on 2021-01-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0036_auto_20210117_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodurinexray',
            name='xray_view',
            field=models.TextField(blank=True),
        ),
    ]
