# Generated by Django 3.1.3 on 2021-01-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0037_auto_20210120_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='age',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='desig',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='married_stat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientoverallmedicaldetails',
            name='organization',
            field=models.CharField(max_length=255),
        ),
    ]
