# Generated by Django 3.1.3 on 2021-01-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0038_auto_20210121_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='waist_hip_ratio',
        ),
    ]
