# Generated by Django 3.1.3 on 2021-02-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0039_remove_patientoverallmedicaldetails_waist_hip_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='chest_pain',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='fainting_spells',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='freq_cold',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='freq_headache',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='hearing_disturb',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='joint_pains',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='short_breath',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='swelling_ankle',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='urinary_disturb',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='vertigo',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='visual_disturb',
        ),
        migrations.RemoveField(
            model_name='patientoverallmedicaldetails',
            name='weight_loss',
        ),
    ]
