# Generated by Django 3.1.3 on 2021-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0040_auto_20210203_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='form7details',
            name='date',
            field=models.DateField(default='2021-01-01', verbose_name='%m/%d/%Y'),
            preserve_default=False,
        ),
    ]
